# Generated by Django 4.1.4 on 2023-01-31 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=240, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=240)),
                ('Price', models.IntegerField()),
                ('created_by', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='', max_length=240, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')])),
                ('last_name', models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=240)),
                ('phone', models.CharField(default=0, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numerics are allowed.')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
